include:
  - path: ./packages/db/docker-compose.yml

services:
    server:
        container_name: xenous-server
        build:
            context: .
            dockerfile: ./apps/server/Dockerfile
            secrets:
              - {source: server_env_local, target: server_env}
              - {source: db_env_local, target: db_env}
        env_file:
          - path: ./.env
            required: false
          - path: ./apps/server/.env.local
            required: false
        ports:
          - 127.0.0.1:3000:3000
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:3000]
            interval: 10s
            timeout: 5s
            retries: 5
    next:
        container_name: xenous-next
        build:
            context: .
            dockerfile: ./apps/next/Dockerfile
            secrets:
              - {source: next_env_local, target: next_env}
        environment:
          - HOSTNAME=0.0.0.0
        env_file:
          - path: ./.env
            required: false
          - path: ./apps/next/.env.local
            required: false
        ports:
          - 127.0.0.1:3001:3001
        depends_on:
            server:
                condition: service_healthy
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:3001]
            interval: 10s
            timeout: 5s
            retries: 5
    tanstack:
        container_name: xenous-tanstack
        build:
            context: .
            dockerfile: ./apps/tanstack/Dockerfile
            secrets:
              - {source: tanstack_env_local, target: tanstack_env}
        environment:
          - HOSTNAME=0.0.0.0
        env_file:
          - path: ./.env
            required: false
          - path: ./apps/tanstack/.env.local
            required: false
        ports:
          - 127.0.0.1:3002:3002
        depends_on:
            server:
                condition: service_healthy
        healthcheck:
            test: [CMD, wget, --no-verbose, --tries=1, --spider, http://127.0.0.1:3002]
            interval: 10s
            timeout: 5s
            retries: 5

secrets:
    server_env_local:
        file: ./apps/server/.env.local
    db_env_local:
        file: ./packages/db/.env.local
    next_env_local:
        file: ./apps/next/.env.local
    tanstack_env_local:
        file: ./apps/tanstack/.env.local
