packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
    '@biomejs/biome': ^2.2.5
    '@dotenvx/dotenvx': ^1.51.0
    '@t3-oss/env-core': ^0.13.8
    '@t3-oss/env-nextjs': ^0.13.8
    jiti: ^2.6.1
    tailwindcss: ^3.4.18
    typescript: ~5.8.3
    zod: ^3.25.76

catalogs:
    node22:
        '@types/node': ^22.11
    react19:
        '@types/react': ~19.0.0
        '@types/react-dom': ~19.0.0
        react: ~19.0.0
        react-dom: ~19.0.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - sharp

patchedDependencies:
    better-auth: patches/better-auth.patch
