packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
    '@better-auth/expo': ^1.6.11
    '@biomejs/biome': ^2.4.15
    '@dotenvx/dotenvx': ^1.66.0
    '@t3-oss/env-core': ^0.13.11
    '@t3-oss/env-nextjs': ^0.13.11
    '@tailwindcss/postcss': ^4.3.0
    '@tanstack/react-form': ^1.32.0
    '@tanstack/react-query': ^5.100.10
    '@tanstack/react-query-devtools': ^5.100.10
    better-auth: ^1.6.11
    jiti: ^2.7.0
    tailwindcss: ^4.3.0
    typescript: ~5.8.3
    zod: ^4.4.3

catalogs:
    node22:
        '@types/node': ^24.12.4
    orpc:
        '@orpc/client': ^1.14.3
        '@orpc/openapi': ^1.14.3
        '@orpc/server': ^1.14.3
        '@orpc/tanstack-query': ^1.14.3
        '@orpc/zod': ^1.14.3
    react19:
        '@types/react': ~19.2.14
        '@types/react-dom': ~19.2.3
        react: ~19.2.6
        react-dom: ~19.2.6

allowBuilds:
    '@parcel/watcher': true
    esbuild: true
    lefthook: true
    msw: true
    sharp: true

minimumReleaseAge: 10080  # one week

hoist: false  # Disable hoisting to isolate dependencies per workspace
nodeLinker: isolated  # Ensure pnpm uses the default "isolated" node_modules structure
linkWorkspacePackages: true  # Auto-link workspace packages when version ranges match
engineStrict: true  # Restrict using incorrect engines
