packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
    '@better-auth/expo': ^1.6.9
    '@biomejs/biome': ^2.4.13
    '@dotenvx/dotenvx': ^1.62.0
    '@t3-oss/env-core': ^0.13.11
    '@t3-oss/env-nextjs': ^0.13.11
    '@tailwindcss/postcss': ^4.2.4
    '@tanstack/react-form': ^1.29.1
    '@tanstack/react-query': ^5.100.1
    '@tanstack/react-query-devtools': ^5.100.1
    better-auth: ^1.6.9
    jiti: ^2.6.1
    tailwindcss: ^4.2.4
    typescript: ~5.8.3
    zod: ^4.3.6

catalogs:
    node22:
        '@types/node': ^24.12.2
    orpc:
        '@orpc/client': ^1.14.0
        '@orpc/openapi': ^1.14.0
        '@orpc/server': ^1.14.0
        '@orpc/tanstack-query': ^1.14.0
        '@orpc/zod': ^1.14.0
    react19:
        '@types/react': ~19.2.14
        '@types/react-dom': ~19.2.3
        react: ~19.2.5
        react-dom: ~19.2.5

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - lefthook
  - msw
  - sharp

minimumReleaseAge: 10080  # one week
